# Generated by Django 4.1 on 2022-12-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0002_rename_name_cookiestand_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookiestand',
            name='hourly_sales',
        ),
        migrations.AlterField(
            model_name='cookiestand',
            name='description',
            field=models.TextField(blank=True, default='nanananana', null=True),
        ),
    ]
