# Generated by Django 4.1 on 2022-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0003_remove_cookiestand_hourly_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiestand',
            name='hourly_sales',
            field=models.TextField(blank=True, default=list),
        ),
    ]
