# Generated by Django 4.1 on 2022-12-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0004_cookiestand_hourly_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiestand',
            name='hourly_sales',
            field=models.TextField(blank=True, default=''),
        ),
    ]
